Ignore any new Strigo field not yet handled
Instead of failing with error like 'TypeError: Class.__init__() got an unexpected keyword argument 'labels''